on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

name: Deploy

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: deploy to github pages
    runs-on: ubuntu-latest

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        if: github.ref_name == 'main'
        uses: actions/configure-pages@v3
        
      - uses: actions/setup-node@v3
        #with:
          #node-version: ''
      - name: setup environment
        run: npm install
      - name: build
        run: npm run build  
      #- name: test
      #  run: npm test
   
      - name: Upload artifact
        if: github.ref_name == 'main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        id: deployment
        uses: actions/deploy-pages@v2